[pantheons.norse]
type = "VM"
[pantheons.greek]
type = "Physical"
[pantheons.roman]
type = "Container"
[pantheons.egyptian]
type = "Cloud"
[pantheons.mesopotamian]
type = "Network"

[realms.erebus]
pantheon = "greek"
owner = "NCG"
status = "active"
form_factor = "laptop"
model = "HP Elitebook 8 G1i 14in"

[realms.olympus]
pantheon = "greek"
owner = "NCG"
status = "active"
form_factor = "laptop"
model = "HP Elitebook 840 G11"

[realms.elysium]
pantheon = "greek"
owner = "Asher Lucas-Cuddeback"
status = "active"
form_factor = "Mini-ITX"

[realms.elysium.hardware]
cpu = "AMD Ryzen 9 9900x3d"
ram_gb = 64
gpu = "Zotac RTX 4070 Twin Edge"
storage_tb = 4

[realms.tartarus]
pantheon = "greek"
owner = "Asher Lucas-Cuddeback"
status = "active"
form_factor = "ATX"

[realms.tartarus.hardware]
cpu = "AMD Ryzen 5 7600X"
ram_gb = 32
gpu = "AMD Radeon RX 6600 XT"
storage_tb = 4


[hosts.hades]
realm = "erebus"
os = "NixOS"
wm = "KDE"
shell = "fish"
terminal_emulator = "kitty"
user = "alucascu"
status = "active"
restic_local = "/home/alucascu/.local/restic-repo/"
restic_ssd = "/run/media/alucascu/Extreme SSD/restic/"

[hosts.hestia]
realm = "elysium"
os = "CachyOS"
wm = "hyprland"
shell = "zsh"
terminal_emulator = "kitty"
user = "asherl"
status = "active"
restic_local = "/home/asherl/.local/restic-repo/"
restic_ssd = "/run/media/asherl/Extreme SSD/restic/"

[hosts.helios]
realm = "erebus"
os = "Windows 11"
shell = "powershell"
user = "ncgmail/alucascuddeback"
terminal_emulator = "wezterm"
status = "unprovisioned"

[hosts.diomedes]
realm = "elysium"
os = "Omarchy"
wm = "hyprland"
shell = "bash"
terminal_emulator = "kitty"
user = "asher"
restic_local = "/home/asher/.local/restic"
restic_ssd = "/run/media/asher/Extreme SSD/restic/"
status = "active"


[hosts.tantalus]
realm = "tartarus"
os = "NixOS"
wm = "KDE"
shell = "fish"
terminal_emulator = "kitty"
user = "alucascu"
status = "active"
restic_local = "/home/alucascu/.local/restic-repo/"
restic_ssd = "/run/media/alucascu/Extreme SSD/restic/"
