{lib, ...}: {
  perSystem = {pkgs, ...}: {
    # Both `nix fmt` and `just fmt` land here, so the exemption below lives in
    # exactly one place. Alejandra's config file accepts only `indentation`,
    # so the exclusions have to be CLI flags.
    formatter = let
      # Generated by `nixos-generate-config` (see `just fetch-hwconfig`),
      # so not ours to style.
      generated = [
        "modules/hosts/odysseus/_hardware-configuration.nix"
        "modules/hosts/tantalus/_hardware-configuration.nix"
      ];

      # Alejandra matches excludes literally against the paths it walks, so
      # `foo.nix` and `./foo.nix` are different strings to it. Walking `.`
      # yields `./…`; naming `modules` explicitly yields bare paths. List both
      # forms so either entry point excludes both files.
      excludes =
        lib.concatMapStringsSep " "
        (p: "--exclude ${p} --exclude ./${p}")
        generated;
    in
      pkgs.writeShellApplication {
        name = "fmt-nix";
        runtimeInputs = [pkgs.alejandra];
        # Alejandra reads stdin when given no path, but `nix fmt` invokes the
        # formatter with no arguments at all — so default to the whole tree
        # unless the caller named a path.
        text = ''
          for arg in "$@"; do
            case "$arg" in
              -*) ;;
              *) exec alejandra ${excludes} "$@" ;;
            esac
          done
          exec alejandra ${excludes} "$@" .
        '';
      };
  };
}
