# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}: {
  imports = [
    "${inputs.nixpkgs}/nixos/modules/hardware/cpu/intel-npu.nix"
    "${inputs.nixpkgs}/nixos/modules/installer/scan/not-detected.nix"
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-4250984e-56eb-4d22-8e20-c3304789c248";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-4250984e-56eb-4d22-8e20-c3304789c248".device = "/dev/disk/by-uuid/4250984e-56eb-4d22-8e20-c3304789c248";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3BB1-79DC";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-8a0d2ba6-be48-40a2-8b7f-920b39918f05";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
